### ISSUE TITLE
[Feature Request] slide down from top activation

### ISSUE THREAD

**Issue by antsh** [rpetrich/libactivator#10]
I was wondering if sliding down from the status bar or from the top of the screen could be an included action in libactivator? I believe it was at some point in PS but has disappeared at some point during development.

**Comment by rpetrich** [comment]
BigBoss requested its removal :(

**Comment by antsh** [comment]
Oh, that sucks haha. The only reason I ask is beacuse sometimes the doubletap on statusbar activates on a single tap when I try to scroll to the top of the page. This happens mostly when there is a little lag and the single tap on the statusbar activates proswitcher as it picks it up as a doubletap? Did bigboss give a reason for it's removal request?

**Comment by rpetrich** [comment]
He has >2 million users, a lot of which will be confused when multiple things happen on a statusbar swipe. In the interests of being a good citizen, I've disabled that feature.

**Comment by antsh** [comment]
Fair enough. Thanks for all the great work on developing for the the iPhone. I couldn't imagine my phone without ps and overboard. Has anyone else reported libactivator sporadically picking up a single tap on the status bar as a double tap?

**Comment by rpetrich** [comment]
Not so far. Is is reproduce-able?

**Comment by antsh** [comment]
Not 100% of the time. It mostly happens in my case when I'm looking at something with a lot of images like facebook or safari for example. When the I tap the status bar top scroll to the top, the iPhone may struggle a bit in my case and ps will activate after the scrolling event as if the status bar was double tapped.

**Comment by sysrage** [comment]
I've seen this happen with swipe down from status bar activation enabled (hidden setting). I have always attributed it to the phone lagging due to something major going on and getting confused.

**Comment by rpetrich** [comment]
I'll look into it... time to use my runloop clogger :)
