### ISSUE TITLE
Unlock + Action

### ISSUE THREAD

**Issue by sagitt** [rpetrich/libactivator#100]
you know that most phone have camera button?

you know htc desire z? or desire hd?

Why you don't add an option that allow the user to hold buttons in lockscreen and activate the action only if the proximity sensor don't see anything? desire z and desire hd have this!!

and why with this yoi don't add the option to launch apps? like unlock + launch app... is useful for camera app on hold vol +- button!

thanks!

**Comment by rpetrich** [comment]
This is a security risk for anyone that has a passcode. I won't be implementing application actions at lock screen ever.

**Comment by sagitt** [comment]
disable with passcode simple :D, or request passcode and do action

**Comment by rpetrich** [comment]
No, that's too much work for a tertiary feature.
