### ISSUE TITLE
[REQ] Action - Take a photo

### ISSUE THREAD

**Issue by XeNoW** [rpetrich/libactivator#101]
Hey,

Thanks for the fix for the lockscreen slide-ins ;)

Now it would be nice if you could add "Take a photo in camera app instead" to the actions. This one should only be used if the camera framework is active.

**Comment by rpetrich** [comment]
No. Enabling this action would require leaving the camera hardware on which would eat battery like crazy.

**Comment by XeNoW** [comment]
I just meant "using the volume button to take a photo within the camera app". I know there is a plugin for this but it's another msa running. I really prefere having all controls in one app.

Otherwise I'll just get SnapTap... ^^

**Comment by rpetrich** [comment]
Oh, I see what you mean now. Yeah, SnapTap already does this I think.
