### ISSUE TITLE
Status Bar Lock Icon not cleared after Activator Unlock

### ISSUE THREAD

**Issue by agkjaha** [rpetrich/libactivator#102]
3GS OS 3.1.2, Activator 1.4.6 but also at least in prior version

If I lock the iPhone or let it autolock with an application open and displayed (not just backgrounded), after an unlock using an Activator gesture (long and short home button press tested), the Lock icon is still displayed in the status bar preventing the time from showing there.

If the Springboard is visible when the iPhone is put into lock mode, the lock icon is properly cleared after an unlock using Activator.

I haven't found a way to clear the condition without locking the iPhone and unlocking without Activator (if an app is displayed) or closing/backgrounding the app so it is not displayed and then locking and unlocking either normally or with Activator.

**Comment by rpetrich** [comment]
Noted. I think the fix I made for a similar bug on 4.0 is causing this issue. I'll look into it.

**Comment by agkjaha** [comment]
Issue still exists in 1.5.0 BETA2.
