### ISSUE TITLE
Feature: Lock orientation

### ISSUE THREAD

**Issue by jasisk** [rpetrich/libactivator#105]
Maybe I'm searching with the wrong keywords but I have not been able to find a solution regarding locking the orientation (preferably, using the OS native lock functionality) with activator. Could this be made a native action?

**Comment by rpetrich** [comment]
Install RotationInhibitor.

**Comment by jasisk** [comment]
Turns out "Landscape Lock Rotation" breaks RotationInhibitor (provides duplicated functionality anyway). I know this is not an issue with RotationInhibitor or Activator but figure it was worth noting for posterity. Thanks!
