### ISSUE TITLE
"Both press" volume action prevents holding the individual buttons

### ISSUE THREAD

**Issue by lunixbochs** [rpetrich/libactivator#107]
Device: iPhone 4 on iOS 4.1

To reproduce:
1. Set an action for "Both press"
2. Hold either volume button.

Expected outcome:
Volume up/down will repeat while you hold the button.

Actual outcome:
Each press of the volume button will only raise/lower the volume one notch, no matter how long it is held.

**Comment by jgastaldello** [comment]
I have this problem as well. Hopefully it can be fixed soon. :)

**Comment by rpetrich** [comment]
This is as designed.

**Comment by lunixbochs** [comment]
why? :/

**Comment by jgastaldello** [comment]
Yeah, why? You are removing a standard feature!?!?!?

**Comment by jgastaldello** [comment]
It's closed :(  Is there any other way to fix this?

**Comment by lunixbochs** [comment]
I just use up/down and down/up instead.

**Comment by jgastaldello** [comment]
Oh well, I will just use those. Thanks.
