### ISSUE TITLE
Exit an app completely

### ISSUE THREAD

**Issue by MaxMan23** [rpetrich/libactivator#109]
Hi,

it would be cool if you can choose under "system actions" a feature "close app completely".

**Comment by grp** [comment]
"Force Quit"

**Comment by MaxMan23** [comment]
Yes this would be a nice feature. So i can select under Home Button "Short Hold" an then select "Force Quit".
Please add this feature.

**Comment by rpetrich** [comment]
I don't think this should be a part of the Activator base package. The most appropriate place would be a part of Backgrounder IMO.
