### ISSUE TITLE
Home Button Short Hold invocation method recently began interfering with Voice Control...

### ISSUE THREAD

**Issue by Bripab007** [rpetrich/libactivator#11]
It seems that with one of the more recent libactivator (or perhaps ProSwitcher) updates is causing the home button short hold to take longer to invoke ProSwitcher, thereby interfering with Voice Control.  I don't recall this happening previously, and I've been using libactivator/ProSwitcher for quite some time (that is to say, it's not user error, since I've been using this invocation method for a while, now, and only recently began to encounter this issue).

**Comment by rpetrich** [comment]
Hmm... can you send more details? I just tried this combination and it works great (short hold == PS; long hold == Voice Controls)

**Comment by Bripab007** [comment]
Well, upon further investigation, it seems to be most prevalent after a fresh reboot or respring. I can get it to happen almost everytime directly afte a reboot. Must take ProSwitcher a hair longer to invoke after a reboot?

**Comment by rpetrich** [comment]
Right after a reboot, there's a whole ton of things loading in the background (Mail, Phone, etc) and the cache for everything is empty so it will definitely be competing with the OS.  I've found that it's best to release it after the short duration even if PS has frozen the screen for a moment while it loads.
