### ISSUE TITLE
New feature Menu cause SafeMode on ipad.

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#110]
Macros? Did I read that right? I couldn't believe it! I was so stoked! But here is the bug: on my iPad 3G 4.2.1 I can make the macros, and assign them to an action, but when I try to execute them, I get SafeMode. Also, when I delete Menus, they show up as blanks when trying to assign something to an action... This was an issue since Beta2, and has not been resolved in Beta3.

Ryan, you rock! I seriously hope I win a large some of money so I can PAY you to teach me some of your mad skillz! Thanks!

**Comment by rpetrich** [comment]
Thanks for reporting. Forgot to test on iPad; next version will remedy this.
