### ISSUE TITLE
Deleted Menus still appear in list

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#112]
1.5.0~BETA3
4.1 3GS
1. Create a Menu
2. Delete the Menu
3. Add an activation and scroll down

One of a two things will happen:
A blank selection will show up (if you did not add the menu to an activator)
A selection will show up (if you added the menu to an activator and then deleted)

**Comment by mattoligy** [comment]
Same here!

**Comment by rpetrich** [comment]
Good catch. I've fixed this in the new beta due out soon.
