### ISSUE TITLE
Lock Screen iPod Controls

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#113]
1.5.0~BETA3
4.1 3GS
1. Choose to show now playing popup (iPod Controls) for Lock Screen > Power Connected
2. The music controls do not appear (as if you were to double press the home button), though if you unlock the phone, the iPod app has started

**Comment by rpetrich** [comment]
Wont Fix. Since iOS4, other applications can take over the media controls, but at startup no app has registered. The workaround for this is to launch the iPod app, but this doesn't work so well when the device is locked. I can't see a way around this.

**Comment by ghost** [comment]
That is understandable.
What about changing the actual popup?
Using Activator: http://img407.imageshack.us/img407/773/wrongj.png
Double pressing home: http://img225.imageshack.us/img225/735/rightpi.png

**Comment by rpetrich** [comment]
Done in next release.
