### ISSUE TITLE
Actions don't work on first try after invoking a [menu]

### ISSUE THREAD

**Issue by mattoligy** [rpetrich/libactivator#115]
After a menu is invoked some actions don't work on a first attempt, activator based And stock IOS (re-invoking a menu, tapping home button once to exit an app, etc) they are dead on first attempt, but then work on a second attempt! Not all actions are affected!

3GS 4.1 activator 1.5~BETA(3)

**Comment by rpetrich** [comment]
Should be fixed in the next beta I think

**Comment by jessthecatmeow** [comment]
I have something to add to this: on the latest release as of 2/8/11, on my iPad 4.2.1, when I access a menu, the screen does not respond until the menu is activated again. I actually would like an activator event that disables touch input, that would be pretty slick. Thanks Ryan.

**Comment by rpetrich** [comment]
Imahottguy: can't repro on 1.5.3-1. Either way, if it's still happening you should open a new ticket with more details.
