### ISSUE TITLE
Activating homescreen-exclusive actions from either the lockscreen or from in an app.

### ISSUE THREAD

**Issue by conradev** [rpetrich/libactivator#116]
Homescreen-exclusive actions should be accessible in either the lockscreen or from in an app, so that when activated, Activator unlocks the device or closes the current app (or both), and performs the action. (This would not override passcode locking). I dont know how it would integrate into Activator perfectly, but i can see it as being a wanted feature.

For example:
- I dock my sleeping iphone and want it to open a nightstand app immediately
- I activate graviboard from in an app and it closes the app and runs graviboard
- I want to search for something, so i use one action and the app closes and switched to Spotlight immediately
  etc.

(For some reason i can't select the feature request label :/)

**Comment by rpetrich** [comment]
I disagree that Activator should switch to the home screen just to perform an action; if actions want to support this ability, they should do so themselves--the built in "launch application" listener has been updated to do so if no passcode has been set.
