### ISSUE TITLE
Removed application action keeps a placeholder

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#117]
1.5.0~RC3
4.1 3GS
1. Set an action (ex MC Pro)
2. Remove MC Pro from Cydia
3. Go back to the activator that you set the action on

The action will be removed, but there will be a blank placeholder with an x instead of the expected (unassigned)

**Comment by rpetrich** [comment]
This is somewhat as designed. It keeps the assignment on the off chance that you reinstall MC Pro. Pressing the (x) will completely clear it.
