### ISSUE TITLE
A problem with single click home

### ISSUE THREAD

**Issue by ttopac** [rpetrich/libactivator#119]
Hi I want to report a bug. This problem occurs with bitesms.

I assigned single press home button to activate overboard in activator, when in springboard.

However when you got a new message and want to dismiss the quickreply of bitesms, you press home button. But uh oh, activator action takes place and overboard screen comes up and the quickreply window doesn't go off.

Thanks.

**Comment by rpetrich** [comment]
Not a bug.

**Comment by ttopac** [comment]
it may not be a bug but it's an issue. Bitesms dev. asked me to report it you.

**Comment by rpetrich** [comment]
There isn't anything actionable on this, so it's closed.
