### ISSUE TITLE
[Req] Allow actions on a secondary screen

### ISSUE THREAD

**Issue by mikedecaro** [rpetrich/libactivator#122]
Hardware like my car radio (Pioneer AppRadio) will display a secondary screen if the app supports it. MotionX, Inrix, Rdio, and Pandora all support this feature. It's just another instance of UIScreen. It would be awesome if Activator could work on this secondary display to change apps, etc, using the slide in actions.

The radio doesn't use anything outside of the official iOS SDK so it shouldn't need any special hooks. The secondary screen can be accessed like this:
UIScreen *external = [[UIScreen screens] objectAtIndex:1];

**Comment by rpetrich** [comment]
Does this secondary screen receive touch events? I don't have any hardware to test this on (only the standard cables I use for DisplayOut and whatnot)

**Comment by mikedecaro** [comment]
Yes, it's a capacitive touch screen. Pandora and Rdio actually change the iPhone display to a static image and only allow input from the second screen. No status bar.

**Comment by mikedecaro** [comment]
I investigated further into this and it seems like it's a bit more complicated than just the extra UIScreen. I wrote a MobileSubstrate plugin that hooks the touchesBegan method of UIControl. My code ran every time I press something on the iPhone screen but wouldn't run when I pressed something on the external screen.

Edit: I've concluded that they implemented iOS integration using the normal display out and added their own API for input from the touch screen. As of now, it seems like activator integration isn't possible.

**Comment by natesymer** [comment]
I hate the ads!!!

**Comment by grp** [comment]
I hate the you!!!

**Comment by rpetrich** [comment]
mikedecaro: you would have to hook `UIView` and not `UIControl` to determine that.

fhsjaagshs: if you press the Donate button, the ads will be removed (you don't need to donate, just click through to the page)

**Comment by natesymer** [comment]
Thanks rpetrich.

**Comment by natesymer** [comment]
Hey rpetrich, would you be willing to help me with some code? I wrote something, but it doesnt work, and it uses activator, so I figured you are the guy to ask about it. 

<a href="http://www.fhsjaagshs.com/">My Website</a>
