### ISSUE TITLE
Conflict with quickdo

### ISSUE THREAD

**Issue by saxlamen** [rpetrich/libactivator#13]
I use quickdo with the method of swiping on the statusbar. But after I upgrade the latest libactivator and proswitcher, it no loger works. Everytime I try to swipe on the statusbar, only sbsettings shows up now. Can the problem be solved?

**Comment by rpetrich** [comment]
What mQuickDo settings do you have? (it has a sea of options all of which setup weird and different combinations of hooks)

Also, please mention which version you have installed (and try on the latest from http://rpetri.ch/repo if you haven't)

**Comment by saxlamen** [comment]
All the settings are "off" except "triggered by statusbar".
I installed the latest version 1.1.0 on the bigboss repo.
I'll try the latest one later~  ^^

**Comment by saxlamen** [comment]
OK, the problem still exists in 1.1.1b5~

**Comment by rpetrich** [comment]
Turns out mQuickDo's status bar gestures no longer work if it gets loaded earlier in the startup process which is colossally dumb. I think I've got a successful workaround ready for the next beta.
