### ISSUE TITLE
Bug: "Now Playing Bar" does not work

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#130]
Sorry, I just noticed this. On my iPad1 3G fw 5.0 when I try to bring up the now playing bar via any action, like double tap status bar, the switcher pops up and closes within like half of a second. I tried this with and without music playing, makes no difference. Thanks, if there is anything I can do to help let me know.

**Comment by rpetrich** [comment]
Looks like a regression on iOS5. Resolved.
