### ISSUE TITLE
Enhancement: Add left/middle/right swipe down actions

### ISSUE THREAD

**Issue by Lunat1k** [rpetrich/libactivator#131]
It would be nice to have more swipe down actions like the swipe up actions. IE Swipe from Left, Swipe from Right, Swipe From Middle.

**Comment by jessthecatmeow** [comment]
I have never had very much luck with the slide-in actions, however I second this :-)

**Comment by rpetrich** [comment]
Resolved in 1.5.9beta1, but only on iOS5.0+--this feature requires new APIs that only iOS5.0+ has

**Comment by Lunat1k** [comment]
Sort of. Swiping down from top left or top right still drops down notification center.
