### ISSUE TITLE
MobileVolumeSound with 1.5.8beta2 doesn´t compatible?

### ISSUE THREAD

**Issue by ag3r** [rpetrich/libactivator#133]
Until update Activator  chpwn´s MobileVolumeSound works perfectly, now it doesnt work...i think it´s possible to be an incompatibility between them...

My mobilesubstrate plugins are :

Winterboard,3G unrestrictor,PopPod,Activator,Appstorelous,AppSync,AttachmentSaver,BugFix_Duplicateicons,BugFix_StuckPages,CallBar,
ColorKeyboard,Copic,Cydelete,Facebreak,FireBreak,FolderCloser,GrowlNotifier,IntelliscreenX, Iconsupport, infinidock,MailTweak,MobileSafety, MobileVolumeSound,NavigateFromMaps, NoNewsIsGoodNews, RemovedSound, SBSettings,SandCastle,SleepFx, Springflash, StartupSound,Vibrafications, Manualcorrect, semitether, libhide, libstatusbar,delword, PreferenceLoader...

**Comment by jessthecatmeow** [comment]
Have you messaged Chpwn? He may have a better idea as to what has broken his tweak. Having 36 installed MobileSubstrate tweaks can be problematic though..

**Comment by rpetrich** [comment]
Resolved in 1.5.9beta1
