### ISSUE TITLE
Bug regarding "Menus"

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#134]
I have a menu assigned to the volume buttons both press, and have a couple of issues. 

First, as of 1.5.8, I cannot access menus via the lock screen. in the past they have worked great, even certain elements of the menu that aren't accessible from the lock screen show on spring board but not lock screen- great, I liked it quite a bit. Now, when I press both volume buttons, the menu does not pop up on the lock screen, rather, it pops under, onto the app or springboard.

Second, for a few items on the menu, the springboard will become unresponsive to touch after being activated. Example: I tap on an SBSettings toggle on my menu, it takes a couple seconds, and then the menu disappears. The app I am in is fine, working, but when I exit to springboard, it becomes unresponsive to touch until I bring up the menu again.

Lastly, when I tap on an SBSettings toggle on my menu, the usual pop up of [toggle] [enabled/disabled] does not occur. This giving no way to know, without pulling up SBSettings, if the toggle was enabled/disabled.

Thank you!

**Comment by rpetrich** [comment]
Menu listeners haven't changed at all since 1.5.2; seems likely that you have a conflict with some other package.
