### ISSUE TITLE
Volume[Up/Down]HoldShort/Volume[DownUp/Updown] feature problem.

### ISSUE THREAD

**Issue by aklef** [rpetrich/libactivator#135]
Volume controls have apparently been worked on in the latest 1.5.8 version of activator, however, some noticeable problems that struck me as being quite intrusive are: 
1. Volume[Up/Down]HoldShort - waits for the exact specified time (~1sec) until providing the desired function HOWEVER immediately reverts to upping or lowering volume at an infuriating rate! Give us some time to take our finger off the bloddy buttons will ya! as in VolumeButtonHoldMoreThan(1sec) => Action => waitAnother(1 sec) => exit.
2. Volume[DownUp/UpDown] - the very first move, whether pressing volumeUp or volumeDown DOES INFACT lower or augment the volume before the desired action takes place! Could you please add a method/function so that it reverts the volume level back to its original level? As in (event) =>action => [Decrement/Increment]VolumeAccordingly => exit.

This is infact my first time posting on these forums/code blogs, for the sole purpose of perfecting my iPhone and getting rid of these infuriating little annoyances that hinder my listening to music, as well as giving my feedback on some cool stuff like activator.

EDIT: another glitch I've seen is the volume controls not responding at all when the device is idle (screen off) and the iPod/Music process has been shut down (i.e. through SBSettings). Perhaps there should be a trigger to first initiate the app (make sure its running) then proceed with the command? Or is this a localized glitch only? Have other user reported anything on this subject?

Cheers.

**Comment by rpetrich** [comment]
Should be remedied in 1.5.9 beta 2
