### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by autopear** [rpetrich/libactivator#136]
Strings below do not localize.
- Single Tap
- Single-tap on statusbar
- Audio
- Press up volume button

They were not in the current release package.

I have replace the latest strings but it still does not show localized strings.

**Comment by rpetrich** [comment]
Should be remedied in the latest 1.5.9 beta 1, but in case they aren't I've created a [separate debug build](http://rpetri.ch/db/libactivator_1.5.9%7Ebeta1_iphoneos-arm.deb) that logs what localization strings it is looking for.

I will commit to delaying the 1.5.9 release until your localizations are ready.

Note: You may not want to leave that version installed indefinitely, it logs a metric ton of things to syslog and as a result will make your device slower than usual.

**Comment by autopear** [comment]
thanks, I'll test it tonight.

BTW, merry Christmas though it's a little late.

发自我的 iPhone

在 2011年12月27日，16:59，Ryan Petrichreply@reply.github.com 写道：

**Comment by autopear** [comment]
All problems are solved except "Audio". Through the log, I found it should be linked with "LISTENER_GROUP_TITLE_Audio" instead of "EVENT_GROUP_TITLE_Audio". I've added the string into English and both Chinese localizations. Everything works fine now.

Also, please remove /Library/Activator/.DS_Store.

**Comment by rpetrich** [comment]
D'oh, that makes sense. Not sure why it was ever categorized as such.
