### ISSUE TITLE
Pressing Volume Down once Mutes device

### ISSUE THREAD

**Issue by moogagot** [rpetrich/libactivator#137]
This is the EXACT same but that happened a month or two ago.
On a fresh re-boot you can press volume down twice and it will work correctly.  After that, a single press of volume down mutes.

Again, this seems to be the exact bug that was causing issues in the past.  Please fix, as this is a truly annoying bug!

Running iPad 1 on an old version of 4.x.

**Comment by rpetrich** [comment]
Regression due to fixing MobileVolumeSound compatibility. Should work again in 1.5.9 beta 2
