### ISSUE TITLE
Phone locks after short power hold event in libactivator

### ISSUE THREAD

**Issue by antsh** [rpetrich/libactivator#14]
When using the new option to launch apps after a short power hold. For example when short power hold is assigned to camera, the app will launch as it's supposed to but the phone will lock immediatley after. Native apps that hook into libactivator such as ps and overboard do not exhibit this behavior. (an alternate way to reach me faster if need be would be @StalinCCCP on Twitter)

**Comment by rpetrich** [comment]
Fixed in 1.2 RC1

**Comment by antsh** [comment]
Confirmed as fixed. Haven't found any other issues so far with the newer build of libactivator.
