### ISSUE TITLE
Activator 1.6.0 and Zephyr

### ISSUE THREAD

**Issue by dinocol** [rpetrich/libactivator#141]
If Zephyr's  Left or Right Edges is ON, Activator's Slide from Bottom, Slide from Bottom Left, and Slide from Bottom Right doesn't seem to respond well. It was working before updating to Activator 1.6.0.

At first i thought it was the latest update of Zephyr, but downgrading zephyr to the first version also came out with the problem.

Zephyr's Left / Right Task Switching is great. But i would prefer using activator for activating the task switcher and setting a few other custom command from slide to bottom.. hope u can fix this. thanks!

**Comment by rpetrich** [comment]
Resolved in 1.6.1 beta 3.
