### ISSUE TITLE
Activating Siri via single home button press causes crash

### ISSUE THREAD

**Issue by kirb** [rpetrich/libactivator#143]
Because of the multitasking gestures for iPads, I barely ever use my home button any more. Since the latest Activator update, I set Siri to activate after I press home once. It all worked until I turned her off. Since then, pressing home causes a crash, even after she's re-enabled. 

I haven't checked whether this is caused by the home button or by the action itself, though. This is all on my iPad 1 with 5.0.1.

**Comment by rpetrich** [comment]
iPad doesn't support Siri.

**Comment by kirb** [comment]
It sort of does - I installed it manually from the 9A406 IPSW, though
images have to be renamed to work and some need resizing.

Back on subject, the crash also happens for Voice Control, on both 5.0
and 5.0.1.

## 

Ad@m
Sent from my iPad

On 07/01/2012, at 2:53 AM, Ryan Petrich
reply@reply.github.com
wrote:

**Comment by rpetrich** [comment]
iPad doesn't have voice control either.

**Comment by kirb** [comment]
Same IPSW.

## 

Ad@m
Sent from my iPad

On 07/01/2012, at 3:09 AM, Ryan Petrich
reply@reply.github.com
wrote:

**Comment by rpetrich** [comment]
SpringBoard's iPad mode is not designed to work with Voice Control or Siri; not an Activator bug.

**Comment by kirb** [comment]
Though both look/act fine (apart from image sizes), it obviously
doesn't happen on iPhone, so I'll take your word.

## 

Ad@m
Sent from my iPad

On 07/01/2012, at 3:28 AM, Ryan Petrich
reply@reply.github.com
wrote:
