### ISSUE TITLE
Screen Dimming in Lockscreen

### ISSUE THREAD

**Issue by HansDieter** [rpetrich/libactivator#145]
Hello,
is it possible to make an activator toggle to disable the screen dimming?
For example if the iphone is locked you tap the toggle to deactivate the automatic dimming an then the screen won´t go black.
This would be useful to control the ipod. You can control the ipod without tapping the sleep button again and again.
In Lockscreen is an option to disable screen dimming while in lockscreen, but this setting must be disabled then not using.
Cause then the iphone is locked and you will recieve an sms the screen wont go black automatic so it would be nice to activate/deactivate this function easy.

HansDieter

**Comment by rpetrich** [comment]
I think there is already an SBSettings toggle to do this. Activator is compatible with SBSettings toggles.
