### ISSUE TITLE
Add Seek Forward/Backward (Rewind) as an action to Audio Actions

### ISSUE THREAD

**Issue by nausher** [rpetrich/libactivator#147]
When listening to Podcasts & Audiobooks the ability to Seek Forward/Backward (Rewind) is a great help.
But currently the only Audio actions available are Next Track, Previous Track and Play/Pause.

GlovePod (https://github.com/rono23/GlovePod) had this feature, but it doesn't work in iOS 5.0.1.

**Comment by rpetrich** [comment]
I disagree that this should be part of the main Activator distribution. Someone else can build it as a plugin.
