### ISSUE TITLE
"Currently Assigned To"

### ISSUE THREAD

**Issue by blsub6** [rpetrich/libactivator#15]
Can you display what the shortcut is currently assigned to instead of having to flip through the list of possible assignments looking for a check mark?

**Comment by rpetrich** [comment]
Possibly, but not for 1.2. I'll mark this as feature request

**Comment by rpetrich** [comment]
Finished in latest beta

**Comment by grp** [comment]
YAY!

**Comment by blsub6** [comment]
Your implementation is beautiful man, thank you for this
