### ISSUE TITLE
 Swipe from Top to Unlock and Music Controls on Lockscreen Interfering With Notification Center Activation

### ISSUE THREAD

**Issue by macman104** [rpetrich/libactivator#155]
Hi,

I hope I do this right, as I've never posted about a bug on github before.  In any case, it seems using certain actions on the lockscreen is causing the notification center to be disabled when I try and then activate it from an application.

This is on an iPhone 4S, 5.0.1
Running Activator 1.6.1

Steps:
Add swipe from top actions to unlock device
Unlock device by swiping from top
Open up application
Attempt to swipe from the top to pull up notification center
- If not in game, nothing happens
- If in a game, the initial black tab to pull down again appears, but never goes away until exiting game
  You can then return to the home screen, and pull down the NC
  This will then reactivate it for use in an app and works as expected.

So far it appears to be on a gesture that involves swiping from the top.  I've observed this on:
swipe from top-left, top-right, top to unlock (one finger)
two finger swipe from top to play/pause music

Let me know if I can provide further information.

Thank you.

**Comment by leoriccio** [comment]
Same issue with the latest beta (1.6.2b1).

**Comment by rpetrich** [comment]
Should be resolved in 1.6.2beta2
