### ISSUE TITLE
Return to 1st SpringBoard page issue

### ISSUE THREAD

**Issue by autopear** [rpetrich/libactivator#156]
To minimize the top running app, it is better to use
{
    struct GSEventRecord record;
    memset(&record, 0, sizeof(record));
    record.type = kGSEventQuitTopApplication ;
    record.timestamp = GSCurrentEventTimestamp();
    GSSendSystemEvent(&record);
}
instead of 
{
    [uic clickedMenuButton];
}

I found that sometimes the clickedMenuButton event will just be sent to something else, which won't close the app.

**Comment by rpetrich** [comment]
Sending the `GSEvent` is asynchronous, so this doesn't work quite right. There's another internal API that works better and I will use that.

**Comment by autopear** [comment]
Do you mean clickedMenuButton?

**Comment by rpetrich** [comment]
No, `-[SBUIController _handleButtonEventToSuspendDisplays:displayWasSuspendedOut:]`

**Comment by autopear** [comment]
Thanks
