### ISSUE TITLE
Difference between top-left and left-top

### ISSUE THREAD

**Issue by autopear** [rpetrich/libactivator#157]
Also top-right and right-top.

**Comment by rpetrich** [comment]
One is the top part of the left edge and the other is the left part of the top edge. Not sure if this is too confusing or not, especially with localization involved. I may just adjust it so there are top-left, top, top-right, right, bottom-right, bottom, bottom-left and left gestures only, and make the corner gestures work from either edge.

**Comment by autopear** [comment]
I think top-left and left-top both refer to the west-north direction. But it seems like you are referring the 11 o'clock and 10 o'clock direction. I don't think there is much difference between these two.

**Comment by rpetrich** [comment]
Decided to suppress them for now. If someone who follows Activator quite closely can't understand what they do, how could anyone else have a chance?
