### ISSUE TITLE
Activator 1.2 causes mobilesubstrate crash

### ISSUE THREAD

**Issue by SkyMatt70** [rpetrich/libactivator#18]
After upgrading to 1.2 and resprung to a crash.  The only solution was to remove Activator and thus ProSwitcher.  Has anyone else had this problem?

**Comment by rpetrich** [comment]
Crash Report required: cydia://package/crash-reporter

**Comment by SkyMatt70** [comment]
http://pastie.org/private/rk9s01bpegyhifvtyhp6jq

**Comment by rpetrich** [comment]
I think we may have discussed this over email, but that crash log points to YourTube crashing in it's initializer; I'm not sure whether or not this is Activator's fault, but I will purchase and look into it further

**Comment by SkyMatt70** [comment]
Without activator and proswitch there is no crash.  Also, downgrading to activator 1.1.0~b7 seems to have fixed the problem as well.
