### ISSUE TITLE
Activator Crash on launch iOS 9.3.3 / iPad Pro 12.9''

### ISSUE THREAD

**Issue by iPhoneAddict** [rpetrich/libactivator#184]
Activator crashes on launch on my iPad Pro 12.9''
- Tested with 1.9.11-b2 and 1.9.10
- Removed other tweaks but keep crashing
- Reinstalled including RacketBootstrap and Flipswitch but Keep crashing

iPad6,8 9.3.3: 1260c4a721607303818185f7951cb8e89745d22a
The following process has crashed:
   /Applications/Activator.app/Activator

Relevant files (e.g. crash log and syslog) are attached.
Details from the user:
-------------------------------------------
Save crash files
-------------------------------------------
/* Generated by CrashReporter (v1.14.0) - cydia://package/crash-reporter */

[Activator-2016-12-22-184348.zip](https://github.com/rpetrich/libactivator/files/669458/Activator-2016-12-22-184348.zip)

**Comment by qrx** [comment]
It crashes upon launch every time on iOS 10.2 on my iPad Pro 12.9" too. Is this issue being looked into?

**Comment by iPhoneAddict** [comment]
It works, it can be launched from the home screen now.
Thank you
