### ISSUE TITLE
Activate Backgrounder via LibActivator?

### ISSUE THREAD

**Issue by PrabhuDeva** [rpetrich/libactivator#19]
Hey Ryan,

do you think there might be a way to integrate Backgrounder into LibActivator, i.e. enable backgrounding of an app not only via hold home button but also any of the other methods available in LibActivator? In the options of Backgrounder there's this option "Toggle backgrounding via: None. For use with external toggle." What's this about? Couldn't this be used with LibActivator??

**Comment by rpetrich** [comment]
It could, but is not within the scope of LibActivator. Perhaps activator support will someday be integrated into Backgrounder, or someone will write the necessary "glue".
