### ISSUE TITLE
Glitch with PowerSelector toggle

### ISSUE THREAD

**Issue by orenmm** [rpetrich/libactivator#196]
Since update to version **1.9.13 RC1**, when pressing **PowerSelector** toggle in CC, the menu dissappears. Downgrading to **1.9.13 beta12** fixes that issue.

**Comment by rpetrich** [comment]
Thanks for reporting. This will be resolved in the next release candidate.

**Comment by orenmm** [comment]
Thank you! After the last update the problem has been solved!
