### ISSUE TITLE
Feature request-Different actions

### ISSUE THREAD

**Issue by danzimm** [rpetrich/libactivator#2]
Single tap homebutton everywhere
slide up from the bottom wherever you are
three finger slide anywhere
home button and lockbutton at the same time (replacing the screenshot)
homebutton hold and screen tap
volume button up
volume button down
volume button and tap
volume button and slide

**Comment by rpetrich** [comment]
Single-tap home button interferes with OS features, so it will always be a hidden event (as it is now)
I will look into the rest of them. Any event that disables OS features is right out.

**Comment by rpetrich** [comment]
Slide up from bottom is implemented (as three separate gestures)
Volume Up/Down and Down/Up are implemented

**Comment by rpetrich** [comment]
Status on the unimplemented ones:
1. **three finger slide anywhere:** won't be doing this. it's too invasive in that it requires hooking a lot of things
2. **home button and lockbutton at the same time:** still considering this
3. **homebutton hold and screen tap:** won't be doing this. it's too difficult to trigger and would be obtrusive
4. **additional volume gestures:** the volume gestures as-is strike a decent balance between convenience and annoyance. replacing the volume buttons is a bad idea in my opinion

**Comment by mcse7en** [comment]
The single home button on the lockscreen doesn't do anything for me. Never has since I originally downloaded Activator at it's release. It just never worked. I'm on 1.4 now and it still doesn't work.

**Comment by rpetrich** [comment]
mcse7en: I've committed a fix for 1.4.2
