### ISSUE TITLE
Double-Home activation issue

### ISSUE THREAD

**Issue by sysrage** [rpetrich/libactivator#20]
I found this when using Stimpys new LockInfo beta. I could not reproduce when I changed the status bar tap-hold to bring up Snappy instead of InfoShade, so it may not be a LibActivator bug. Just figured I would post it both places in case.
- Double-press home set to bring up ProSwitcher.
- Tap and hold status bar set to bring up LockInfo's InfoShade.

1) Tap-hold on status bar, InfoShade comes up.
2) Press the home button to close InfoShade.
3) Tap-Hold on status bar, InfoShade comes up again.
3) Press the home button to close InfoShade. ProSwitcher opens.

It seems as if it's registering the two home presses as a double-press even though there can be a great deal of time between presses and it still happens.

**Comment by sysrage** [comment]
Seems to be a LockInfo problem. It's worse with the latest LockInfo and Snappy doesn't have this problem. Closing...

**Comment by rpetrich** [comment]
In the next release I will be adding a global hook for extensions to "cancel"; this will ensure that "home to close" is consistent between extensions :)
