### ISSUE TITLE
Settings.app crashes with short hold setting

### ISSUE THREAD

**Issue by pheraph** [rpetrich/libactivator#21]
I have a problem with libactivator and Lockinfo (http://david.ashman.com/lockinfo). I tried to assign the Short Hold (Home button) as so called InfoShade-Activation, but when I select it in the settings it crashes and returns to the springboard. The other Homebutton activations work.

This is what Syslog says about it:

Mar  8 11:45:24 iPhone Preferences[528]: libactivator: Configuring com.ashman.lockinfo.infoshade
Mar  8 11:45:26 iPhone Preferences[528]: **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSCFArray insertObject:atIndex:]: attempt to insert nil'

**Comment by rpetrich** [comment]
Hmm... this is odd. Can you install kennytm's crash-reporter via Cydia and have it send me a crash report?

**Comment by rpetrich** [comment]
I think I've fixed this so I'm closing. If not, please reopen.
