### ISSUE TITLE
Answer etc. actions

### ISSUE THREAD

**Issue by sagitt** [rpetrich/libactivator#23]
Why you don't add a new actions like answer or dismiss phone call :)?

**Comment by rpetrich** [comment]
I don't see these as being that useful. Unless I receive a patch that provides them, I don't expect to be adding them to the base Activator package

**Comment by sagitt** [comment]
See callcontroller or similar app by mcleaner... Like answer or dismiss a call with a shake  :)

**Comment by rpetrich** [comment]
Someone could make an external package if they so choose

**Comment by sagitt** [comment]
yes but is necessary the action "in call" or not?

**Comment by rpetrich** [comment]
Not sure what you mean.

**Comment by sagitt** [comment]
nothing :)
