### ISSUE TITLE
Bottom gestures don't work after opening any apps installed. After respring OK. 

### ISSUE THREAD

**Issue by alexling** [rpetrich/libactivator#26]
I have now libactivator 1.3~rc4 and Quickdo 1.4.4 installed. After respring, everything works fine. I can swipe from the bottom to activate the gestures. But once I open an app then quit it, the gestures don't work anymore. Then I respring, they work again. Anyone else has the same problem? Can you fix it in the final version of 1.3? The problem has existed since 1.2. If I install 1.1 version, no such problem. Thanks in advance.

**Comment by rpetrich** [comment]
I will look into it, but the QuickDo support is very much trial and error. I don't know if it will make it for 1.3

**Comment by alexling** [comment]
Something in Quickdo is very useful, it can call a menu to do things with one gesture instead of doing one thing by one gesture. Or you can think about combing several actions in one gesture to customize own menu. :P

**Comment by rpetrich** [comment]
A customizable Activator menu is in alpha testing with VIP testers

**Comment by alexling** [comment]
Does RC5 fix this issue?

**Comment by alexling** [comment]
1.3.1 b1 still doesn't work
