### ISSUE TITLE
Volume Up/Down actions can be accidentally triggered while changing volume

### ISSUE THREAD

**Issue by lunixbochs** [rpetrich/libactivator#28]
If you're changing the volume and decide you made it too loud or quiet, you might immediately press the other volume button... alas, this can trigger a volume up/down action.

I suggest two improvements to fix this:
1. Don't activate if the first button was pressed more than once in a row (with a timeout, perhaps allow activating with that button again when the volume HUD fades)
2. Don't activate if the first button was held for very long.

These fixes will allow changing the volume to coexist more happily with libactivator's volume button actions.

**Comment by rpetrich** [comment]
I like these heuristics. They make sense.

Added to the to do list

**Comment by rpetrich** [comment]
Added in my local source copy. Will be added to public version soon
