### ISSUE TITLE
Triple home button click

### ISSUE THREAD

**Issue by eweezy** [rpetrich/libactivator#3]
Would it be possible to add a "three click home button" option as an activation method? I would love this because I really like my phone favorites as the double click.

Thank you,
Eric

**Comment by rpetrich** [comment]
Added to my mental to do list

**Comment by aussietanker** [comment]
can i also wote for this ... i absolutely LOVE this application on my iPhone 4, but would really like to have it extended with a triple click option (would also love to be able to get the "slide in gestures" to work :() thank you - rod

**Comment by mattoligy** [comment]
Totally agree! Triple click home button is an essential requirement IMO! Home button is the most used event on an iPhone and it needs to be Totally utilised! Long hold home button should be added too...

**Comment by rpetrich** [comment]
In 1.5.8
