### ISSUE TITLE
Free-fall Activation Method

### ISSUE THREAD

**Issue by knek** [rpetrich/libactivator#36]
Could free-fall be added as an activation method (i.e. all three axes of the accelerometer give very near zero readings)? I would love to be able to trigger something by just giving my phone a little toss.

I've tried to look at the code and could probably lend a hand if I could figure out how to get the accelerometer data but due to my limited (a.k.a. zero) iPhone OS development experience I'm not able to add it completely. From what I understand, other events like shaking are detected by the OS (but free-fall is not) so I understand if it isn't easy/possible to do this.

Thank you, and thanks for all your wonderful work with the iPhone.

**Comment by rpetrich** [comment]
Though this is possible, I'm not sure it's a good idea to encourage people to put their phones/pods/pads into freefall. Convince me otherwise.
