### ISSUE TITLE
MenuPressSingle event sent after unhandled MenuHoldShort

### ISSUE THREAD

**Issue by ashikase** [rpetrich/libactivator#37]
Issue:
I have an extension that is registered to receive both MenuHoldShort and MenuPressSingle. When I receive a MenuHoldShort, if I do not mark it as handled, I then receive a MenuPressSingle event. I believe that this behavior is incorrect.

Reasoning:
If I were to register for and then receive a MenuPressDouble, and mark it as unhandled, I would not expect to then receive a MenuPressSingle. Just because they both use the menu button, they are two separate gestures. I feel that the same logic applies to MenuShortHold.

**Comment by rpetrich** [comment]
I will be committing a fix shortly. Do you have a test case I can run it against? (just flying by the seat of my pants at the moment)
