### ISSUE TITLE
Volume Display sometimes sticks when used to sleep

### ISSUE THREAD

**Issue by lunixbochs** [rpetrich/libactivator#40]
Volume display tap is a really convenient way to sleep a phone with a broken power button, but sometimes the hit area doesn't go away after using it to sleep - you need to pop it up and tap it a few more times.

**Comment by rpetrich** [comment]
"you need to pop it up and tap it a few more times"
What do you mean by that?

**Comment by lunixbochs** [comment]
I'm talking about the volume HUD

**Comment by rpetrich** [comment]
I think this is fixed (as of 1.4.1)
