### ISSUE TITLE
Home button double press at lockscreen and iPod controls

### ISSUE THREAD

**Issue by PrabhuDeva** [rpetrich/libactivator#42]
Scenario: I've assigned double home button press to invoking the iPod popup anywhere, i.e. also on the lockscreen. Reason is I'd like to be able to wake my iPhone from sleep mode with a double home button press, the hit the iPod button on the popup and thus quickly go to the iPod app from sleep mode without having to slide to unlock, look for iPod app and tap it. This works fine when iPod is not playing.

However, when iPod is playing, home button double press does not invoke the iPod popup but instead invokes the standard iPod controls integrated in the lockscreen clock, which is not intended since it does not have the "iPod" button as the popup does. Using other methods (for example short home button hold) to invoke the iPod popup at lockscreen does obviously not cause this. Could you therefore somehow prevent the standard iPod controls (the one integrated in the lockscreen clock) from popping up when having home button double press assigned to iPod (or generally, assigned to anything) at lockscreen?

More generally, if you assign home button double press at lockscreen to anything (say, SBSettings) and thereby invoke SBSettings and double press home button again with SBSettings still open, the standard lockscreen iPod controls also appear behing SBSettings which in my opinon is not really desired at all since you assigned another action than iPod controls to home button double press.

**Comment by rpetrich** [comment]
There are a few bugs here:
1. iPod button is allowed from lock screen. This should be disallowed as it allows someone to subvert the passcode on the device
2. Double-pressing at the lock screen shows the now playing lockscreen plugin not the now playing alert.
3. Either SBSettings isn't handling the "deactivate event" or it isn't being sent. I will look into this before escalating to BigBoss

Also, I think it should be possible to allow actions that would unlock the device if the user allows it and understands that it can subvert their passcode. An option perhaps?

**Comment by PrabhuDeva** [comment]
Well, from my perspective, there should be an option to allow actions unlocking the device such as the iPod button on the now playing alert bubble.

By the way, for users of LockInfo who have replaced the stock lock screen clock with the Lock Weather plugin (kind of a lock screen clock with integrated weather) using the now playing alert bubble works better than the standard now playing plugin integrated into the standard clock, because the standard now playing alert cannot be activated in the Lock Weather clock and you'd get messy results with two clocks showing on lock screen. Therefore, another reasong to keep allowing the now playing alert bubble on the lock screen even if it might be difficult to handle the passcode issue.
