### ISSUE TITLE
[Feature Request] Add a Preference to revert to 1.3 behavior regarding the home button.

### ISSUE THREAD

**Issue by riannucci** [rpetrich/libactivator#44]
Specifically, I usually like to set my backgrounder interfaces to use the single-click Home button (as this is the natural action for dealing with starting/stopping applications). As of 1.3.1, however, there's some different behavior in that the single-press home event still gets passed through to the OS. This is especially noticeable in Kirikae, as the app which is normally listed as the 'Foreground' app gets backgrounded at the same time that Kirikae comes up. Tapping the foreground app (in Kirikae) only closes the Kirikae popup (with the idea that the Foreground app is still in the Foreground).

With Activator 1.3, tapping the foreground app would go back to the foreground app. In 1.3.1, it goes to Springboard (because the previously-foregrounded app is now minimized).  I understand the motivation behind this change (Issue #41), but it would be marvelous to allow the end user to opt-in to this behavior, if they really do want the home button to be completely re-assigned.

The behavioral change is noticeable on other Backgrounder front-ends (well... multifl0w anyway). I also tried ProSwitcher, but because of the way it works, it's semi-natural to have the app auto-minimize.

Fantastic library, btw... I haven't gotten to do any dev stuff on the iPhone yet, but I admire the architecture behind libactivator :D.

**Comment by rpetrich** [comment]
This behaviour was changed for safety reasons--some users were getting "stuck" inside of applications. The older behaviour was an oversight. If extensions like Kirikae and multifl0w require different behaviour from the single press home event, they are free to add it themselves.
