### ISSUE TITLE
Configuring "Swipe Down" crashes settings app

### ISSUE THREAD

**Issue by jpolopski** [rpetrich/libactivator#46]
I am trying to assign an action to the "Swipe Down" gesture.  When I go into Activator (through settings) and try to assign an action to "Swipe Down", it crashes back to the SpringBoard.  This happens 100% of the time, regardless of where I am trying to configure the gesture ("Anywhere", "At Home Screen", "In Application", and "At Lock Screen").  Approximately 1 second after I tap on "Swipe Down" to configure the gesture, it crashes back to SpringBoard.  I can assign actions to every other button / gesture with the exception of "Swipe Down".

If you would like me to retrieve logs or crash reports, let me know and I'll post them for you to take a look at.  My device is a 3GS running OS 3.0.1.

Thanks.

**Comment by rpetrich** [comment]
Can you send a crash report using: http://rpetri.ch/p?crash-reporter

**Comment by jpolopski** [comment]
I installed crash reporter and syslogd.  When I run crash reporter and it finishes "symbolicating" the crash, it does not identify a primary, secondary, or tertiary suspect.  I can view the crash log and syslog, but those are my only options in crash reporter (I don't get an option to send the crash report).

Did you want me to copy / paste the contents of both the crash log and syslog into an email and send it to you?

**Comment by jpolopski** [comment]
I managed to fix the problem.  After upgrading to version 1.3.2 of Activator, I failed to notice that you added an option to "reset settings".  I decided to give that a try last night, and now everything is working normally.  I no longer experience a crash.

**Comment by rpetrich** [comment]
Weird. Looks like your settings were corrupt. I'll close the issue ticket.
