### ISSUE TITLE
Feature Request: BT Keyboard Function keys

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#48]
Allow modifying the behavior of the function keys of BT keyboards, such as the Apple keyboard. I would love to be able to set the F1 key as the home button, the F2 to launch a favorite app, etc. I thought that Activator would be perfect for this. Thanks for your work, you are awesome!!!

**Comment by jessthecatmeow** [comment]
Wow I'm stupid lol. Never mind, sorry for the ignorance! (found my own answer)

**Comment by rpetrich** [comment]
Only works with BTstack for the moment. I may add support for the native keyboarding available in OS 3.2+ at some point

**Comment by jessthecatmeow** [comment]
Very cool. Thanks for the reply, it wasn't until a minute ago that I had the idea to check BTStack for activator support.
