### ISSUE TITLE
b6 on Cydia ( 2010.01.10) borks both ProSwitcher & Overboard

### ISSUE THREAD

**Issue by z31r4m** [rpetrich/libactivator#5]
Ummm, installed the updated b6 build from the booleanmagic/repo...

Running Overboard now throws the msg that 'MobileSubstrate is required, exiting'.

Proswitch works but only from invoking via icon on Springboard. Gestures do not work nor show up in the Activator Prefs. Please advise...

**Comment by z31r4m** [comment]
The issues I described above are fixed with 1.1b7. Re-added booleanmagic repo back and got betas incl the b7 LibActivator.. which now works.

**Comment by z31r4m** [comment]
Um, commented and closed this bug..

**Comment by rpetrich** [comment]
great that it's now working :)

**Comment by z31r4m** [comment]
Ryan, just out of curiousity, and off-bug/list, could you tell me what the problem was with b6? One of these days when I grow up (more) I'd like to get into programming. I'm curious as to why b6 barfed...perms? unlinked files? ...?

**Comment by rpetrich** [comment]
What happened in this case was b4-5 put files in /User (which is a symlink to /var/mobile); I was informed by saurik that doing this was improper and that files should be instead be in /var/mobile. I moved the files there in b6 causing Cydia to remove /User when the package was upgraded. /User is required for a number of things :S
