### ISSUE TITLE
swipe up from bottom left/right bug 

### ISSUE THREAD

**Issue by colmiak** [rpetrich/libactivator#51]
there's a pretty huge bug with activator's swipe from bottom function during a phone a call. 
to recreate the bug, this is what I do:

I make a phone call and then I press the home button to go do something else and I have the green double status bar that indicates I'm on a call. I swipe up on the bottom right (really swiping up on left or anywhere on the bottom produces the bug) and nothing happens but the middle area of my phone becomes unresponsive. I can't swipe left or right correctly but I can still use some areas like the status bar to bring up sbsettings and respring to fix the problem. I tried using different things to activate to make sure it wasn't just one app that produced the bug, both bitesms' quick compose and lockinfo's infoshade produce the bug. 

there is also a bug in the activator section of the settings app that removes the left top arrow that bring you back to the original settings page. I have to kill settings I order to be able to access my other settings again. this has happened twice but I'm not sure how to reproduce it.

**Comment by rpetrich** [comment]
Can you send more details? OS version? Screenshots? List of installed packages?

(keep in mind I don't have a 4.0 device that is capable of sending calls)

**Comment by colmiak** [comment]
I'm on 4.0, iPhone 3gs.

List of packages installed: 
Activator 1.4 beta 2
Bitesms 4.92
iFile
libdispllaystack
libweather
Lockinfo
pincrsh
preferenceloader
Remove Recents
SBSettings/toggles
Winterboard
3g unrestrictor 

i tried turning off every extension one by one in sbsettings to see if one was clashing with activator (actually i was just trying to find out which app was causing the problem, i didnt pin it down right away) but even having only activartor's as the only extension running produces the same bug

http://twitpic.com/21aiu8

i should note that the screen becomes unresponsive only after i invoke any activation method (from swipe left/reight up from bottom)

basically everything below the green status bar becomes unresponsive. i can tap on the green and bring back up the call and that gives me back some responsiveness. i can tap on speaker or the dialpad sometimes. after i end the call, i can swipe left and right on some areas on the springboard but i still dont have full responsiveness.

one area i always have responsiveness is the status bar and the area where the respring button of sbsettings is. it's varies a bit because sometime i can still tap on icons on my dock, for example the phone icon and my mal icon. i notice that i can almosta always swipe to the right to get to spotlight but the only way to get out of spotliight is to use the home button. i cant seem to swipe to my second springboard page at all. i'm doing some testing right now as i type and im tapping on every icon on my page; i can tap and open every icon except everything on the very right, safari's column.

 im respringing to reproduce the issue and see if the same areas of the screen do the same thing again. okay, if im in the call and i can still get to my second page if i continually swipe around the top middle area. once i end the call, i cant get to my second page. 

OH. okay. i see why i couldn't get to my second page. it's because i was starting the swipe from that right dead zone. i think this might be relevant because for this test i only set swipe from bottom right and my right side is now unresponsive to touch, on springboard and in app. the rest of the screen works fine. 

okay so i set the left side to activate quick and compose (already had sbsettings set for the right) and now both the left and right sides are dead. only the middle responds to touch. the middle being my bitesms and mail columns. 

setting only the swipe up from bottom option makes the middle area (bite and mail columns) unresponsive. 

that's pretty much all i can think of to help with that.

actually last note on that, if i tried to use the ANY activation method /while/ i still have any swipe up from bottom activation /set/ then that areas becomes unresponsive after i invoke any activation method while in a call. i tested with displaytap, volume up/down, status bar swipe down/left/right.

**Comment by rpetrich** [comment]
I will adjust the swipe gesture to occur at a different time; this might help. (though I can't test calls, so I can't be sure)

Try 1.4.0 beta 3

**Comment by colmiak** [comment]
Its not on cydia for me, is it the same beta repo as always?

**Comment by colmiak** [comment]
installed rc1, unfortunerly the bug is still present.

**Comment by rpetrich** [comment]
I think I may have tracked this down. Turns out _any_ double-sized statusbar triggers it. Voice Memos is one example, tethering another.

I'm working on a fix that should be in RC2
