### ISSUE TITLE
Fix iPod pop-up controls for iOS4

### ISSUE THREAD

**Issue by PrabhuDeva** [rpetrich/libactivator#52]
In iOS 4, the "old" iPod pop-up controls have been discontinued and integrated into the task switcher. However, via Activator it is still possible to invoke the pop-up controls (which I personally like much more than the new integrated controls since the old pop-up has on-screen volume controls and simply looks better). However, when the iPod app/process is not running in the background, the former "iPod" button on the pop-up (which could be used to open the main iPod app) is not labelled "iPod" anymore (it is empty now) and tapping it does not open the iPod app. It does work properly when the iPod is running in the background, though.

Do you think you could be able fix this somehow? Even if it is not directly related to Activator, but on iOS 4 Activator is the only way of still using the old pop-up controls.

**Comment by rpetrich** [comment]
This popup has atrophied since 3.2 and I have no intention of fixing Apple's bugs.  If it becomes a big issue, it is simpler to just disable this action or switch over to using the new "music page" of the switcher bar.
