### ISSUE TITLE
Settings app occasionally crashes after update to Activator 1.4 beta 2

### ISSUE THREAD

**Issue by PrabhuDeva** [rpetrich/libactivator#53]
After having updated to 1.4 beta 2, when using the iOS 4 task switcher to switch between several running system apps such as Mail, iPod, and Settings, the Settings app sometimes either crashes when opening it via the switcher or it disappears completely from the switcher while switching between other apps (thus obviously crashing unnoticed in the background). This happens both when using the stock Double Home Press activation method or any other method selected via Activator.

Of course, I'm not 100% sure this is caused by Activator (can't think of any plausible relation to Activator, as as matter of fact), but I'm pretty sure this first happened after updating to 1.4 beta 2 (have not installed/updated any other Cydia apps at the same time).

**Comment by rpetrich** [comment]
As usual, use Crash Reporter to generate crash reports: http://rpetri.ch/p?crash-reporter

**Comment by PrabhuDeva** [comment]
This problem of crashing Settings.app seems to have disappeared with 1.4.0 RC1...

**Comment by rpetrich** [comment]
I'll mark this as closed, but because I've made a lot of changes to the Settings app again, you can reopen it if necessary
