### ISSUE TITLE
Partial uncompatibility with firmware 3.2

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#54]
After installing Activator 1.40b2 after respringing apparently nothing happens but rebooting completely the iPad or turning it off and on result in a mess up. The unlock slide bar is bigger and after unlocking it it seems to be in a big iphone with only a small 4 iconed dock, black bacground and the same icon layout as in the iphone/ipod. Also not all controls respond so it's quite hard. The only way to restore it is starting safe mode from SBsettings and then respringing.
This issue was present also in b1

**Comment by rpetrich** [comment]
The "big iPod touch mode" occurs when some APIs are used before they're ready. I don't think this is Activator's doing, but I will review all the relevant code before closing this

**Comment by ghost** [comment]
I see... by the way it only occurs with activator 1.40. Installing back 1.32 solve the issue.

**Comment by rpetrich** [comment]
Ah, found it. Fixed in the upcoming beta 3
