### ISSUE TITLE
Settings (backgrounding?) bug

### ISSUE THREAD

**Issue by colmiak** [rpetrich/libactivator#55]
this on an iPhone 3gs, with Activator 1.4 beta 2 on 4.0

i did just have that other bug i told you about in settings app. i think what happens is that i went into activator settings, set something, came back out to activators main settings (the one with  "Anywhere" at the top), pressed the home button to do something else and then when i reopened Settings app and  tried to tap the left arrow to go back to the main Settings page. this is what happens and i was just able to reproduce it: http://twitpic.com/21ao6y

so to be a bit more clear on how to reproduce that one:
1. open settings app
2. go to activator preferences main panel
3. press home button (which backgrounds Settings and im guessing this is where the problem lies)
4. re-open Settings app (which bring you back to Activaror's main settings panel)
5. Tap top left arrow to return to Settings main panel

edit: ugh sorry, i just saw the other issue with a similar bug, should have posted this there. anyway, unlike the other issue/bug, i havent had my settings app crash by itself. just hangs like in the screenshot until i kill it myself.

**Comment by rpetrich** [comment]
Is this on 4.0 by any chance? If so, try beta 3. I /may/ have fixed it.

**Comment by colmiak** [comment]
yea, on 4.0. sorry. always forget details. I'm about to try out the new beta

**Comment by colmiak** [comment]
I installed rc1, bug is still there present by repeating the same steps.

**Comment by PrabhuDeva** [comment]
I'm getting a similar bug with 1.4.0. RC1 on my 3GS with 4.0 CFW...

**Comment by rpetrich** [comment]
Trying a fix for RC2...
