### ISSUE TITLE
(Request) Holding a volume button as an Activation Method

### ISSUE THREAD

**Issue by SilentMike** [rpetrich/libactivator#56]
Would be awesome if each volume button, when being held down for a second or two, served as new activation methods. Hope you consider it for a future update.

Thanks,
-Mike

**Comment by XeNoW** [comment]
+1 for this. reminds me of my old Sony Ericsson mobile phone. VolumeButtonExtendern does this as well but it's bugged with iOS 4.0. Please add this to the todo list =)

**Comment by rpetrich** [comment]
Added to the todo list
