### ISSUE TITLE
Bring back old way of using the Slide In Gestures

### ISSUE THREAD

**Issue by PrabhuDeva** [rpetrich/libactivator#57]
I really love the Slide In Gestures. However, at least since I've updated to 1.4.0 RC1, they now work a little bit different than they used to: Before, the defined action for each Slide In Gesture was activated once you dragged your finger the required distance up from the screen bottom without having to lift the finger from the screen. But now, the actions assigned to the Slide In Gestures are only performed once you lift your finger from the screen (you can actually slide your finger in from the bottom, drag it to the top of the screen, hold it there for a minute and then release, action is performed). Only little difference, but for me, this completely breaks the previous usability experience of the Slide In Gestures. I urge you to bring back the old behavior: Perform the action instantly as soon as the finger is moved the required distance without having to release it first. I can't really describe why I hate the new behavior, I just do. The old one was just so much better. :)

**Comment by PrabhuDeva** [comment]
And generally, I get the feeling that the Slide In Gestures are less responsive than they were before, i.e. they do not work more often than before. Especially given this "unresponsiveness", it'd be great to have the old way of being activated with having to lift your finger from the screen, since as it is now, you do not really know whether your finger was already dragged long enough (and thus can be lifted) or not, or whether this time the gesture doen't work at all...

**Comment by rpetrich** [comment]
I agree, it would be nice to have the old behaviour for slide in gestures. I had to change it to this because the switcher bar won't show at all on 4.0 if there are active touches. I'll mark this a feature request.

Sensitivity of the gestures haven't changed, only the requirement that the finger be lifted to complete them.

**Comment by PrabhuDeva** [comment]
Okay. Regarding that sensitivity: To me it seems that now when I slide in my finger from below the screen, much more often than before the respective dock icon is "tapped" instead than registering the slide gesture. (Do you understand what I'm trying to say? ;) )

**Comment by rpetrich** [comment]
I do, but that hasn't changed from earlier versions

**Comment by rpetrich** [comment]
Reverted to earlier behaviour in 1.4.0 with workaround for FailSwitcher

**Comment by PrabhuDeva** [comment]
Hey, thanks for answering, although i'm not sure what FailSwitcher is supposed to be.

I just installed the update to 1.4.1, and now my Slide In gestures are completely broken: Using them to acitvate the switcher most of the time results in the switcher sliding up and down for some time, sometimes locking the Springboard with an opened switcher that shows no apps at all. Using the gestures to lock my iPhone results in the display dimming and re-activating multiple times until finally locking as desired.

**Comment by PrabhuDeva** [comment]
Still have no idea what exactly you meant by that FailSwitcher, but after installing the new version 1.4.2 everything works fine again. Once again, thanks so much for your quick and great work, Ryan!

**Comment by rpetrich** [comment]
Yeah, a last minute commit for 1.4.1 that I forgot to test messed this up. d'oh!

**Comment by aussietanker** [comment]
mmm i can't seem to get these slide in gestures to work at all ... perhaps i am doing them incorrectly ... iphone 4 on 4.1 ... any tips appreciated
