### ISSUE TITLE
[Req] Control Native Backgrounding

### ISSUE THREAD

**Issue by XeNoW** [rpetrich/libactivator#58]
I don't know if this should be a feature of Backgrounder or activator... 

But anyway it would be nice if you could controll native backgrounding with an activation method. Therefore it would be necessary to hook in the way native backgrounding works. I think it would be way easier if activator adds an action that allows you to use the home button in an app to kill/close the app instead of keeping it running in the backround/recent dock (same as deleting it from the recent list). That way you could use an other methode to trigger the normal homebutton action --> native backgrounding/placing the app in the recent dock/natively going back to homescreen.

This would be a major improvement to native backgrounding and would give much more control over your device.

**Comment by rpetrich** [comment]
This should likely be a part of Backgrounder.
