### ISSUE TITLE
Problem with Activator 1.4.0 RC1

### ISSUE THREAD

**Issue by Emeric** [rpetrich/libactivator#60]
Hello,

I have a problem with Activator 1.4.0 RC1 and my 3GS v3.1.2 old iBoot.

I installed Activator 1.4.0 RC1 but at each restart of my iPhone, this last starts in Safe Mode.

When I uninstalled 1.4.0 RC1 Acitvator and I reinstalled Activator 1.3.2, everything works perfectly.

Can the problem be solved ?

Thank you by advance.

PS: afflicted for my poor english

**Comment by rpetrich** [comment]
Please send a crash report using this software: http://rpetri.ch/p?crash-reporter

**Comment by Emeric** [comment]
OK, I have installed Crash reporter. When i launch it, i have a crash in "Mobile" folder with three possibilites "View crash log", "View syslog" and "dyld" in Tertiary suspects folder.

You can see the log file here : http://pastie.org/private/ogkoctw4s0c5dstg2ozua

**Comment by rpetrich** [comment]
Appears to be a problem with SMSHelper and not Activator. Closed.

**Comment by Emeric** [comment]
Thank you very much rpetrich.
I uninstalled SMS Helper and the iPhone boot and reboot normally.
