### ISSUE TITLE
iPod controls on double-click Home button not working

### ISSUE THREAD

**Issue by mcse7en** [rpetrich/libactivator#63]
Re: the bug I (@mc_se7en) posted with screenshot on twitter

In Activator 1.4, double clicking the Home button no longer invokes the iPod controls along with a third button for whatever action is assigned (in this case I was using Backgrounder, but also tried LockInfo's InfoShade and SBSettings). Now it just goes straight to the assigned action. I haven't tried it on the LockScreen, because I have no use for it there (what action could I possibly want to invoke there?)

If you need anything else let me know and I'll make it happen.

This is with iPod actually playing music on an iPod2,1 running 4.0 official release build.

I have Multitasking, Gas Gauge Battery and Unified iPod enabled through WinterBoard (themed the system file that contains the device capabilities).

**Comment by rpetrich** [comment]
This is as-designed for iOS4.0; the old behaviour no longer makes sense now that we have the multitasking bar and there's no space to add a button.
