### ISSUE TITLE
Ads get stuck in the whole Settings application

### ISSUE THREAD

**Issue by mcse7en** [rpetrich/libactivator#64]
This happens on iOS 4 with multitasking.

Do this:

Settings > Activator > (Pick one, doesn't matter) > (Any one works) > STOP

Now quit Settings. Reopen Settings. It launches to the main settings page with the ad from Activator. No matter where you go in the app, that ad stays there. You can quit it and reopen and it stays there. The only way to get rid of the ad is to quit Settings, bring up the multitasking dock, hold the icon, hit the minus button, then reopen Settings.

**Comment by rpetrich** [comment]
Hmm... I can confirm this. Will be fixed for the next release. It should disappear if you exit the Activator settings pane manually before minimizing Settings.

**Comment by rpetrich** [comment]
Committed a fix for 1.4.1
