### ISSUE TITLE
1.4.0 Issues with freeing memory in SBSettings or with MemoryTap

### ISSUE THREAD

**Issue by agkjaha** [rpetrich/libactivator#65]
iPhone 3GS OS 3.1.2 (PwnageTool)
The latest release is causing issues with "Free Up Memory" in SBSettings and MemoryTap (from Cydia) which claims to use the SBSettings code. Both of these have had issues when invoked several times in succession (reliable when used 1-2 x with apps open) but the latest Activator release seems to break MemoryTap completely and make "Free Up Memory" in Cydia far less stable.

MemoryTap seems to hang completely displaying "Freeing Memory" with the rotating progress indicator until SpringBoard crashes after about a minute. "Free Up Memory" has become far less stable with all apps closing and springboard crashes occurring frequently even on one invocation with apps open.

Yup, I know in theory, the OS should do its' thing and free memory as it's required but I find them extremely useful for tracking apps that have allocated far more memory than normal after they've been running a while. Example Twitteriffic and TWC can both become memory hogs until restarted if they've been used for a while (Twitteriffic: opening a bunch of web pages from tweets, performing serches, etc / TWC accessing map pages and forecasts of multiple locations).

This is a definite change in behavior from earlier Activator versions that I noticed immediately after upgrading to V 1.4.0 with no other changes to the iPhone.

**Comment by rpetrich** [comment]
I can't get FreeMemory to work on either my iPhone 4 or my 3G S running 3.1.2 even when reverting back to 1.3.2--it doesn't load on iPhone4 and just displays a progress spinner for a bit before crashing on 3.1.2. I consider it broken

SBSettings's free memory works fine on both of my devices

I don't recommend using any of these free memory tweaks. If an app is using too much memory, close it completely. iOS4.0's built-in multitasking will do this for you.
