### ISSUE TITLE
Shake gesture not recognized after invoking and closing SBSettings

### ISSUE THREAD

**Issue by agkjaha** [rpetrich/libactivator#66]
iPhone 3GS OS 3.1.2 (PwnageTool)

After opening (and closing) SBSettings, Activator fails to recognize the Shake gesture until after opening another app from the Springboard, closing an app or invoking Kirikae and switching to an app or back to the Springboard.

This issue seems to have been in every version of Activator I've used since it was first included with a Kirikae release.

SBSettings invocation configured to left-->right status bar swipe. Shake configured to invoke Kirikae when in an app, and configured to Sleep when in Springboard or on Lock Screen.

**Comment by rpetrich** [comment]
I have verified this bug and traced it to something that isn't being set right in SBSettings. I'll look into it with BigBoss.
