### ISSUE TITLE
Feature Request: Add 'Headset Click' as action.

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#68]
What I mean is, to say that I select 'Long Press' as the method and have it act as the headset button. The advantage would be for those who don't have headphones with buttons, could activate iPod voice controls and also do double and triple clicks to advance or rewind playback. Does this make any sense?

**Comment by rpetrich** [comment]
For now, I think the short hold and single press events are sufficient. I will mark this as "Feature Request"
