### ISSUE TITLE
Activator "gone" from settings?

### ISSUE THREAD

**Issue by Dedrick** [rpetrich/libactivator#69]
I just jb:ed my iPhone 4 with iOS 4.0.1 and installed sbsettings with activator. I also installed BiteSMS which uses some features of it. Everythings been working fine since I jb:ed 2 days ago, but now the "activator"-menu in iPhone settings is gone and I cant use any gestures or access sbsettings at all. 

Ive tried reinstallring / removing a couple of times, but I cant seem to fix this issue, activator just wont show up again. It all happened out of the blue when I was about to show sbsettings to him. Really odd. :/

**Comment by rpetrich** [comment]
Perhaps you have installed something that is causing your phone to enter Safe Mode?
