### ISSUE TITLE
slide in gesture from top

### ISSUE THREAD

**Issue by alexling** [rpetrich/libactivator#7]
hi, i have just updated libactivator to b8. But one problem still exists. Since b5, when i activate slide in gesture (from bottom, from bottom-left or -right), i cannot make it when i slide from bottom, instead i can do it by sliding from the top... is it a bug that no one yet raised? i am sure it works fine when i have b4 installed. pls check it, thanks in advance. :-)

**Comment by jerryen** [comment]
Are you sure you're doing it correctly? Your finger should start below the screen and then slide onto it. So if you have slide in from bottom set, you place your finger between the screen and the home button and then slide up onto the screen and lift your finger. You don't have to slide it very far; about 1cm is far enough.

**Comment by alexling** [comment]
i am pretty sure i am doing it in a correct way. i can activate it from top by about 1cm drag.

**Comment by alexling** [comment]
i have quickdo installed. is that the conflict?

**Comment by sysrage** [comment]
Probably, yes. Although the slide up from bottom gestures really don't work well at all. It was explained to me that this is because the touch digitizers do not work well on the edges. mQuickDo has that annoying bar at the bottom by default, though. So that's most likely causing your problem.

**Comment by rpetrich** [comment]
I added compatibility with mQuickDo awhile back, but my trial has since run out. It should still work

**Comment by alexling** [comment]
the bar of my quickdo is on top, so i should be able to use the "slide in gesture from bottom" to activate PS, shouldn't I?but it doesn't work at all!!!

**Comment by rpetrich** [comment]
Ah, I wasn't aware that QuickDo has an option to put the bar over the statusbar (it seems like that won't interact with SBSettings too well). I've added additional checks to make sure then bar is at the bottom, before using it for the slide gestures. Should be in rc3

**Comment by joeheathen** [comment]
Since updating to RC3, The Quickdo bar is very squirrely about being activated. Uninstalling lib activator returns Quickdo to normal behavior. I have my bar set to the bottom, and Proswitcher set to NOT use the bottom gestures. Anywhere I can download the previous version of Libactivator, or any idea if the next version will have a fix?

**Comment by joeheathen** [comment]
All better with today's release! Thanks.

**Comment by rpetrich** [comment]
Excellent!
