### ISSUE TITLE
Activator causing some screen problems when turning screen on off on repeatedly using POWER button!!!

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#70]
Hi,

After installing activator there is a problem that has arisen. The following scenarios happen when turning the screen on after installing sbsettings:

1) The screen comes on, flashes for a second, the comes on for good

2) I try to turn the screen on off on quickly and the screen sometimes doesnt come back on, i have to press one more time to get it on.

3) The screen lags and comes on if you try to turn it on normally without trying again for a couple of seconds.

I know this because I uninstalled sbsettings and the problem went away. did it twice even restored. 

Anyone with sbsettings installed? Please try to play with your power button repeatedly, try to turn on off on your screen fast and see if any of these scanarios happen. 

Please visit my thread at MacRumors.com to see what others have to say.

http://forums.macrumors.com/showthread.php?t=984558

Thanks
AE

**Comment by ghost** [comment]
Please visit my thread at MacRumors.com to see what others have to say.

http://forums.macrumors.com/showthread.php?t=984558

**Comment by rpetrich** [comment]
I've committed a fix that should bring Activator much closer to the expected behavior. Let me know how Activator 1.4.1 goes.

**Comment by ghost** [comment]
Hi Ryan,

I don't know if you will see this but since I don't have your contact info, I'm goin to just give this a try for now. Regarding the new ver 1.4.1. First of all I would like to thank you for comitting your time to this update. So the updat improved the above mentioned scenarios but didn't eliminate them. Meaning that for example in scanerio #1 (above) the screen now flashes faster. So you don't see the flash as much but it's still there. It's about a 0.5-1s delay then it works normally. Scanerio #2 has not improved, as sometimes pressing the lock button to turn my screen back on, after turnin it on and off previously, will do nothing, forcing me to press again to turn it on. Scanerio #3 does seem to have disappeared. I now encounter scanerio 1&2 only. Once again thanks for your hard work and hope to heat back from you. I added you on twitter if you need anymore feedback let me know.

Thank you,
AE

**Comment by cyrax83** [comment]
Hi,
I am having the exact same issues as described above. 1&2 are indeed a big issue, causing me to uninstall activator. I had to restore my phone and re-install apps one at a time to pinpoint the issue.

If you need any further information you can contact me.
Thanks
