### ISSUE TITLE
keyboard + slide in from bottom

### ISSUE THREAD

**Issue by JStraitiff** [rpetrich/libactivator#72]
the slide in from bottom gesture interferes with the space key on the keyboard and makes it hard to type properly.

**Comment by XeNoW** [comment]
Hmm somehow I never noticed a problem with that. I actually like it to be able to open my switcher with slide in while keyboard is opened!

**Comment by rpetrich** [comment]
Finally found a way to remedy this due to some new APIs Apple introduced. On iOS5.0, Activator 1.5.9beta1 will allow touches to pass through to the app with slide gestures.
