### ISSUE TITLE
Application Switcher

### ISSUE THREAD

**Issue by jerryen** [rpetrich/libactivator#73]
If Activator is used to show the application switcher, icons which are hidden via SBSettings/Poof aren't shown in the application switcher. The hidden icons appear when double pressing home is used to show the application switcher.

**Comment by rpetrich** [comment]
I can't reproduce this. Can you give me exact steps?

**Comment by jerryen** [comment]
I have Cydia hidden through SBSettings and Settings hidden and docked in SBSettings. They both have already been opened and the SBSettings app (More button) has also been opened. When I double tap the home button to open the application switcher, SBSettings, Cydia, and Settings are in there. If I close the switcher and activate it using activator (I have tried double tap status bar and all 3 slide in from bottom gestures), those 3 apps do not show up.

**Comment by rpetrich** [comment]
The method I was using to activate the switcher has slightly different behaviour than double-tapping the home button normally does. Fixed for 1.4.1 :)
