### ISSUE TITLE
[Feature Request] Docked

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#74]
I would love it to be able to launch any application when docked into specific plugs.

A screen (much like the Nike+ pairing screen) with "Plug your iDevice in to pair" could be used to get the identifier of each different type of dock, then the user could choose specific applications to launch.

More specific for me would be the TomTom car kit with one of the many TomTom apps.

**Comment by rpetrich** [comment]
Though this is a good idea, I don't have any hardware to test it on. Perhaps someone who does will make this.
