### ISSUE TITLE
Settings don't display current state

### ISSUE THREAD

**Issue by bengennaria** [rpetrich/libactivator#76]
In the settings for Activator it does not display the currently assigned action for anything. Actions are still active and functional, but display as unassigned and no checkmark is next to the current action. Tapping to uncheck and tapping again to re-check the action causes the checkmark to appear, but "Currently assigned to" still displays unassigned and the checkmark disappears if you tap the back button and re-enter.

**Comment by rpetrich** [comment]
I can't reproduce this. Can you give me more details?

(iOS version, device, and detailed step-by-step following a "Reset Settings")

**Comment by bengennaria** [comment]
iOS v.4.0.1, iPhone4, after resetting settings I enter the Activator settings and experience the behavior described above. I enter settings for Anywhere, choose Short Hold for Home Button. It appears unassigned, I tap Backgrounder and nothing happens, I tap it again and it is checked. It still shows as unassigned. I exit settings and the action executes as expected. Re-enter settings and my action is no longer checked and displays as unassigned. It appears to be a purely cosmetic bug at this point and could very well be a conflict with something else on my iPhone, I'm just not sure what.

**Comment by bengennaria** [comment]
Hmmm, further details. It appears to be related to old settings in some way. The Reset Settings button cleared only actions created recently. Older actions created with 1.3.x or possibly 1.4.0 were untouched. I can create/remove new actions and the settings display correctly. Perhaps a strange permissions bug? Where does activator store its actions?

**Comment by rpetrich** [comment]
Settings are stored in /var/mobile/Library/Caches/libactivator.plist
