### ISSUE TITLE
Activating within Cydia is no longer allowed

### ISSUE THREAD

**Issue by Elit3** [rpetrich/libactivator#77]
These 2 updates will destroy your ability to activate anything while you are in Cydia.

**Comment by bengennaria** [comment]
This appears to be designed behavior. Commit 5134a1786c4b3b20382d disables activator in Cydia. I'm not sure why though. I agree that it is irritating though.

**Comment by grp** [comment]
This is because a badly-written Activator extension could prevent you from using Cydia: and thus, prevent you from even being able to uninstall that extension!

**Comment by JamieD360** [comment]
This is really annoying. This isn't intentional right? Please fix.

**Comment by bengennaria** [comment]
The reasoning chpwn gave is very logical. I would appreciate something in the settings to enable activator in Cydia. I think adding a strong warning that an ill-behaved or buggy extension could break Cydia would be sufficient and of course the option would be off by default.

**Comment by rpetrich** [comment]
chpwn: A malicious extension could still do that.

This is to prevent against users doing silly things while Cydia is installing something or to avoid a restart. Ideally I would like to detect when Cydia has started installing and disable for the duration of the install, but there is no provision for that currently.

**Comment by bengennaria** [comment]
Until that kind of check in Cydia is available, I think it would still be good to have the option to enable activator within Cydia. Given of course that the end user is warned that his actions could have severe consequences.

**Comment by rpetrich** [comment]
It's now a hidden option. Those that know enough to find it know enough to understand the ramifications
