### ISSUE TITLE
Native iPod Controls?

### ISSUE THREAD

**Issue by JamieD360** [rpetrich/libactivator#78]
Would it be possible to add the option to bring up the system's native iPod Controls? When on the Lockscreen, Activator's iPod Controls don't stop the screen from timing out. And you can't rewind/fast-forward with these controls.

EDIT: iOS 3.x. Not everyone's running iOS 4.x and Whited00r could really do with this feature. whited00r.com (I'm the iPod firmware developer there)

**Comment by rpetrich** [comment]
iOS4.0's native controls refuse to show on the lock screen.

**Comment by JamieD360** [comment]
Sorry i forgot to say iOS 3.x
