### ISSUE TITLE
Activator does not keep activation method

### ISSUE THREAD

**Issue by dave1075** [rpetrich/libactivator#8]
Updated today and now cannot set activation method in activator. Looks like it does not save set activation method in activator (it does not show set method when leaving activator settings and going back in again). Can you help/solve?

Thanks

**Comment by rpetrich** [comment]
What are the permissions on this file: /var/mobile/Library/Caches/libactivator.plist
Can mobile read/write to it? I'm thinking perhaps your permissions are messed up...

**Comment by dave1075** [comment]
yes, read/write attributes are ok.

**Comment by rpetrich** [comment]
Can you uninstall, delete the file, and then reinstall?

**Comment by dave1075** [comment]
It's running! I unistalled, deleted the file, rebootet and reinstalled.

Thanks!
