### ISSUE TITLE
After 1.4.1 and 1.4.2 volume HUD isn't shown sometimes

### ISSUE THREAD

**Issue by ttopac** [rpetrich/libactivator#82]
As stated in title. It usually happens if memory drops under 60mb. I've iPhone 4 and my installed activator apps: notifiedpro sbsettings snappy springflash. Also I've bitesms but I don't choose using activator. Volume HUD comes back after sleeping the device and unlocking afterwards. 

Edit: I think its a biteSMS issue. For now it can be closed.

**Comment by rpetrich** [comment]
I'll close it then. If it is indeed an Activator issue, it can be reopened.
