### ISSUE TITLE
[REQUEST] A way to configure defaults?

### ISSUE THREAD

**Issue by JamieD360** [rpetrich/libactivator#83]
I think it would be pretty handy if we were able to set the defaults. So when Activator gets reset, it will revert to these settings, rather than the Activator defaults.

Even if it's just a .plist like this: /Library/Activator/Defaults.plist (the same format as libactivator.plist of course)
Then Activator will revert to these after a reset.

**Comment by rpetrich** [comment]
I disagree. Reset to defaults should give a pristine fresh state.
