### ISSUE TITLE
Statusbar screws up

### ISSUE THREAD

**Issue by ttopac** [rpetrich/libactivator#84]
Hi, there's a statusbar bug in notified pro or in activator, presumably in activator. Here's how to reproduce: 

1) doubletap to statusbar is the activation method for me, so activate notified pro
2) close it
3) open an app that changes statusbar, i have sychronicity installed so sync with itunes in my example.
4) statusbar is like the images http://yfrog.com/jw7sgj http://yfrog.com/5o2patj

**Comment by rpetrich** [comment]
Please give me a procedure that doesn't involve paying for two commercial applications.

**Comment by ttopac** [comment]
Sorry rpetrich I only reproduced that way. I also notified authors of these 2 apps but I'd like to know if you can look at it.

**Comment by rpetrich** [comment]
Get in contact with the developers of those apps; I don't think this is Activator caused.
