### ISSUE TITLE
Swipe on status bar also scrolls to top

### ISSUE THREAD

**Issue by 0xced** [rpetrich/libactivator#85]
Swiping left or right on the status bar also make the current UIScrollView scroll to top. It would be great if this could be avoided.

**Comment by bloudermilk** [comment]
Swiping down has the same effect. Would love to see this bug get squashed

**Comment by rpetrich** [comment]
This has been on my list for a long time now :P

**Comment by rpetrich** [comment]
Next version will include this.

**Comment by 0xced** [comment]
Thanks :-)

**Comment by bloudermilk** [comment]
Awesome! Looking forward to it :)
