### ISSUE TITLE
A feature request about lock-screen mode

### ISSUE THREAD

**Issue by ttopac** [rpetrich/libactivator#86]
In lockscreen lots of activator based programs (for example sbsettings, notified pro etc.) doesn't override apple's lockscreen dim timer and if you're doing some job on them, screen dims automatically after 10 secs. For example if try to take a note in fast notes(in sbsettings) you can't do because the screen dims. 

So it'd be nice if activator adds a timer override feature in lock-screen activated apps. Thanks for your consideration.

**Comment by rpetrich** [comment]
This is out of the scope of Activator.
