### ISSUE TITLE
allow in Cydia

### ISSUE THREAD

**Issue by Takaba** [rpetrich/libactivator#88]
Hi there,

Since the Last Update
Please allow you the choice for use Activator in Cydia !

Thanks to Give you the choice

Because I use Activator via Sbsetting to enable the wifi in cydia if have forget to enable wifi before
Now with the last activator 1.4.2 open cydia ----> if have forget enable wifi ----> close cydia -----> enable wifi ----> open Cydia <---- not Cool

**Comment by rpetrich** [comment]
Duplicate of Issue 77
