### ISSUE TITLE
In 1.1.0 when double pressing the lock button causes safe mode.

### ISSUE THREAD

**Issue by mattyb123** [rpetrich/libactivator#9]
As the title says, since the 1.1.0 update a couple of days ago me and a few others I know get safe mode if you double press the lock button

**Comment by rpetrich** [comment]
Will need crash report for this please (for best results, use kennytm's Crash Reporter and have syslog installed)

**Comment by mattyb123** [comment]
I have just come to simulate the crash again and it appears to be fixed and on my friends it has been too. Sorry about that :)
