### ISSUE TITLE
Activator 1.4.3 and Firmwar 3.1.2

### ISSUE THREAD

**Issue by Takaba** [rpetrich/libactivator#90]
Dear Mister Ryan,

Don't Forget 3.x Firmware User's

The Last Update 1.4.3 of Activator introduce 2 new Bug on 3.1.2
Volume Button slide Down and Up Doesn't work 
New Feature push on down volume button Doesn't Work

And The Know Bug :
Double Tap Lock Button Doesn't Work

Dear Mister Ryan I have downgrade to 1.4.0 and I have win a new Bug 
Double Tap Lock Button are inverted work on springboard now Cool
and doesn't work on Lock screen !

Lol version <----> Ryan Petrich Has my Iphone Please Donate to Ryan for     resolvation of this 3 Bug

Ryan you are cool again, please Rock Planet of 3.x Firmware User 

Take Care with Your Iphone Don't Push The Button and Rest Cool :-)

Brice From France

**Comment by rpetrich** [comment]
I think most of these issues are fixed in the next release, but since this report is vague and argumentative I'm closing it.
