### ISSUE TITLE
only springboard action in application

### ISSUE THREAD

**Issue by sagitt** [rpetrich/libactivator#92]
hi, i associated the "power button" action to shake in springboard but sometimes it works in applications.. like eBuddy Pro or Facebook... so if i shake the device in the app it lock the device.

**Comment by rpetrich** [comment]
Can't reproduce this with stock Activator.
Do you have multifl0w installed? The current version has a bug that doesn't hide the springboard views when activating an app.

**Comment by sagitt** [comment]
no multiflow, it happen only sometime!
