### ISSUE TITLE
Minor cosmetic issue with SBSettings toggle notifications

### ISSUE THREAD

**Issue by mwhdc** [rpetrich/libactivator#93]
SBSettings toggle notifications are about twice as tall as they should be when a toggle is invoked in an app or at the home screen. The text is top aligned and there are several lines of empty space below. On the lock screen, these notifications are the proper height.

Thanks for coding this and releasing it for free - it's indispensable.

**Comment by grp** [comment]
Agreed; this is a bug.

**Comment by rpetrich** [comment]
Fixed in the next release :)
