### ISSUE TITLE
[BUG] Volume Button - Both Pressed + Locked device

### ISSUE THREAD

**Issue by XeNoW** [rpetrich/libactivator#95]
I'm using "Volume Button - Both Pressed" for Play/Pause music anywhere. If music is playing and the device is locked it works well. If no music is playing and the device is locked/screen is turned off for some time, "Start"/"Both Pressed" doesn't work anymore. It DOES work shortly after the divice got locked. Is this intended to save battery or a bug?

**Comment by rpetrich** [comment]
Yes, the device puts the CPU into a low power mode. This is as designed.
