### ISSUE TITLE
1.4.4: iOS 3.1.3 volume display stays on screen forever

### ISSUE THREAD

**Issue by HunterZ** [rpetrich/libactivator#96]
After updating via Cydia to libActivator v1.4.4 on my iPod Touch 2 with iOS 3.1.3, the volume display that appears when I hit the volume buttons on the side of my iPod no longer fades out - it just stays on screen forever. I know this is due to activator because I temporarily disabled it and the problem went away.

I also noticed that I can make it get unstuck by adjusting the volume via SBSettings.

Edit: I should mention that I have no actions assigned to any of the volume-related events. Interestingly, if I do assign an action to some of them it makes the problem go away. As a workaround, I've currently assigned up,down and down,up to SBSettings since I'm not likely to accidentally trigger those events (and, unlike some of the other events, they do not cause activator to prevent the volume from continuing to increase while holding the volume button).

Edit 2: Actually, it looks like even that isn't enough to make it go away most of the time, but if I actually hit, say, up-down to trigger SBSettings it will then fade out. Better than having it stuck there for now, but I'd rather roll back to Activator 1.4.3 if I could do so easily.

Edit 3: Got 1.4.3 (from here: http://www.spiritjb.org/2010/09/activator-143-final-osx-iphone-4.html ) and rolled back via dpkg -i. Issue is gone. I'll wait for a newer version than 1.4.4 to show up on Cydia before updating again.

**Comment by rpetrich** [comment]
Fixed

**Comment by HunterZ** [comment]
Seems to work fine now, thanks!
