### ISSUE TITLE
Overboard + Activator issue: Pinch-in in spotlight

### ISSUE THREAD

**Issue by sagitt** [rpetrich/libactivator#97]
Associate pinch-in to overboard by activator and do this:
1. Go to spotlight
2. Open overboard by pinch-in
3. Exit from overboard clicking on a "empty zone"
4. Try again to do pinch in spotlight zone

you can see that pinch close the keyboard and not open overboard!

if you can't reproduce it, try to do pinch-in in rapid sequence

**Comment by rpetrich** [comment]
I'm going to close this one. You shouldn't actually be able to do the pinch gesture on spotlight :P
