### ISSUE TITLE
Bug: Pressing volume down key mutes iPad

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#98]
It doesn't seem to matter what the volume is set at, if I press the vol down key, it will mute my iPad in 1-3 clicks. These clicks are not long presses, but clicks, as if to lower the volume by one tick. I do have actions set to the long presses for both up and down vol keys, but this seems independent of that. I can verify that it is activator, because when I rename the dylib inside /usr/lib/ and respring, the issue goes away. I am using the latest revision of activator as of 9/29/10. I can provide any additional info, if needed. Thanks. 

Thank you so much for your software! I am an owner of nearly every paid product that you have, and would love to donate, but $$ is too tight unfortunately. Thanks for what you do!

**Comment by rpetrich** [comment]
Found the source of this bug. This will be fixed in the next release :)

**Comment by jessthecatmeow** [comment]
You rock. Seriously! Is I love you too much? I don't think so! Lol
