### ISSUE TITLE
Visual volume pression

### ISSUE THREAD

**Issue by sagitt** [rpetrich/libactivator#99]
associate "quick compose" of bitesms to visual pression of volume popup, press volume up and press to a empty zone of screen it open QC too.. try bitesms QC and you can see that it open QC only on the popup pression.

Anyway if you don't associate QC to visual pression, try to HOLD vol down\up in lockscreen you see the popup volume! (default vol up\down hold don't show it!)

**Comment by rpetrich** [comment]
This has always been broken on 4.0; I've committed a fix :)
